apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependency-track

configMapGenerator:
- name: dt-api-application-properties
  literals:
  - ALPINE_DATABASE_MODE=external
  - ALPINE_DATABASE_URL=jdbc:postgresql://localhost:5432/dependency-track
  - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
  - ALPINE_DATABASE_USERNAME=dependency-track-user

- name: dt-sql-proxy-properties
  literals:
  - DT_DB_CONNECTION=dependency-track-307423:us-central1:dependency-track-db

images:
  - name: dependency-track-apiserver
    newName: us-central1-docker.pkg.dev/dependency-track-307423/dependency-track/apiserver
    newTag: "4.1.0"
  - name: cloud-sql-proxy
    newName: gcr.io/cloudsql-docker/gce-proxy
    newTag: "1.17"

resources:
- pvc.yaml
- statefulset.yaml
- service.yaml
- ingress.yaml
