apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependency-track

configMapGenerator:
- name: dt-frontend-application-properties
  literals:
    - API_BASE_URL=https://dtapi.demogarden.app

images:
  - name: dependency-track-frontend
    newName: us-central1-docker.pkg.dev/dependency-track-307423/dependency-track/frontend
    newTag: 1.2.0

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
